const SHOP_SCOPE_KEYWORDS = [
  "robotiokit",
  "product",
  "products",
  "category",
  "categories",
  "part",
  "parts",
  "component",
  "components",
  "robot",
  "kit",
  "kits",
  "price",
  "budget",
  "cheap",
  "compare",
  "vs",
  "voltage",
  "spec",
  "compatible",
  "compatibility",
  "available",
  "stock",
  "count",
  "total",
  "number of",
  "store",
  "location",
  "address",
  "pickup",
  "order",
  "delivery",
  "shipping",
  "payment",
  "khqr",
  "aba",
  "bank",
  "cart",
  "checkout",
  "buy",
  "recommend",
  "beginner",
  "starter",
  "intermediate",
  "advanced",
  "esp32",
  "esp 32",
  "arduino",
  "arduin",
  "raspberry pi",
  "sensor",
  "ultrasonic",
  "ultrasnic",
  "hc-sr04",
  "sr04",
  "tcrt5000",
  "line tracking",
  "motor",
  "servo",
  "driver",
  "l298n",
  "bts7960",
  "uln2003",
  "drv8833",
  "mg996r",
  "stm32",
  "rfid",
  "gps",
  "lcd",
  "flame",
  "rain",
  "soil",
  "sound",
  "ldr",
  "hall",
  "bme280",
  "bmp280",
  "dht22",
  "relay",
  "buzzer",
  "battery",
  "pwm",
  "module",
  "controller",
  "iot",
  "line follower",
  "obstacle",
  "bluetooth",
  "wifi",
  "environment",
  "monitoring",
  "temperature",
  "humidity",
  "wireless",
  "display",
  "oled",
  "lcd",
  "restart",
  "restarting",
  "brownout",
  "lora",
  "return",
  "cancel",
  "refund",
  "order status",
  "track order",
  "ផលិតផល",
  "គ្រឿងបន្លាស់",
  "ឧបករណ៍",
  "រ៉ូបូត",
  "ឈុត",
  "តម្លៃ",
  "ថោក",
  "ដឹកជញ្ជូន",
  "បង់ប្រាក់",
  "ទូទាត់",
  "ការបញ្ជាទិញ",
  "ប្តូរ",
  "ត្រឡប់",
  "បោះបង់",
  "សងប្រាក់"
];

const SHOP_SCOPE_PATTERNS = [
  /\bunder\s*\$?\s*\d+(?:\.\d+)?/i,
  /\bbelow\s*\$?\s*\d+(?:\.\d+)?/i,
  /\bless than\s*\$?\s*\d+(?:\.\d+)?/i,
  /\b\d+\s*v(?:\s*-\s*\d+\s*v)?\b/i,
  /(?:ក្រោម|តិចជាង|មិនលើស)\s*\$?\s*\d+(?:\.\d+)?/i
];

export function isInShopScope(input = "") {
  if (!input) {
    return true;
  }

  if (SHOP_SCOPE_KEYWORDS.some((term) => input.includes(term.toLowerCase()))) {
    return true;
  }

  return SHOP_SCOPE_PATTERNS.some((pattern) => pattern.test(input));
}
